//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by altacast.rc
//
#define IDI_ICON1                       101
#define ID_TRAYICON                     101
#define IDD_ALTACAST_CONFIG              102
#define ID_STATUSPANE                   102
#define IDD_EDIT_METADATA               103
#define IDR_POPUP                       104
#define IDC_SHOWONSTARTUP               105
#define IDD_CONFIG                      105
#define IDD_PROPPAGE_LARGE              107
#define IDR_CONTEXT                     107
#define IDB_LIVE_ON                     109
#define IDB_LIVE_OFF                    110
#define IDR_MAINFRAME                   111
#define IDR_MAINMENU                    112
#define IDD_ABOUT                       113
#define IDB_LOGO                        115
#define IDR_ICON                        116
#define IDB_ASIO                        119
#define IDD_DUMMY                       122
#define IDB_SMALLLOGO                   124
#define IDD_FINDWINDOW_DLG              125
#define IDR_SYSTRAY                     126
#define IDR_SYSTRAY_MENU                130
#define ID_QUIT                         200
#define IDD_DIALOG1                     301
#define IDD_ALTACAST                     301
#define IDD_PROPPAGE_LARGE1             302
#define IDD_PROPPAGE_LARGE2             303
#define IDC_CONNECT                     1000
#define IDC_HIDE_BUTTON                 1000
#define IDC_EDIT_CONFIG                 1001
#define IDC_LOCK_METADATA               1001
#define IDC_ADD_ENCODER                 1001
#define IDC_MANUALEDIT_METADATA         1002
#define IDC_DESTINATION_LOCATION        1004
#define IDC_ENCODERS                    1004
#define IDC_KBPS_SENT                   1005
#define IDC_TAB1                        1005
#define IDC_BITRATE                     1006
#define IDC_METADATA                    1007
#define IDC_STATUS                      1008
#define IDC_QUALITY                     1008
#define IDC_APPENDSTRING                1008
#define IDC_SAMPLERATE                  1009
#define IDC_CHANNELS                    1010
#define IDC_SERVER_IP                   1013
#define IDC_SERVER_PORT                 1014
#define IDC_PASSWORD                    1015
#define IDC_MOUNTPOINT                  1016
#define IDC_SERVER_TYPE                 1017
#define IDC_ENCODER_TYPE                1018
#define IDC_PUBLIC                      1018
#define IDC_RECONNECTSECS               1019
#define IDC_STREAMNAME                  1019
#define IDC_STREAMDESC                  1020
#define IDC_LIVEREC                     1021
#define IDC_STREAMURL                   1021
#define IDC_SAVESTREAM                  1022
#define IDC_STREAMGENRE                 1022
#define IDC_SAVEWAV                     1023
#define IDC_ICQ                         1023
#define IDC_ARCHIVE_DIRECTORY           1024
#define IDC_AIM                         1024
#define IDC_LOGLEVEL                    1025
#define IDC_IRC                         1025
#define IDC_LOGFILE                     1026
#define IDC_RECDEVICES                  1027
#define IDC_RECVOLUME                   1028
#define IDC_AUTOCONNECT                 1029
#define IDC_RECCARDS                    1030
#define IDC_METADATA_INTERVAL           1032
#define IDC_META_URL                    1034
#define IDC_META_FILE                   1035
#define IDC_METAURL                     1037
#define IDC_METAFILE                    1038
#define IDC_METADISABLE                 1039
#define IDC_VERSION                     1043
#define IDC_METER                       1044
#define IDC_LAMEPRESET                  1046
#define IDC_VUONOFF                     1047
#define IDC_STATIC_STATUS               1048
#define IDC_SHOWHIDE                    1049
#define IDC_SHOWMAIN                    1050
#define IDC_FINDWINDOW                  1051
#define IDC_WINDOWCLASS                 1052
#define IDC_REMOVESTRING                1055
#define IDC_REMOVESTRINGAFTER           1055
#define IDC_WINDOWTITLEGRAB             1056
#define IDC_GRABSTATIC                  1057
#define IDC_REMOVESTRINGBEFORE          1058
#define IDC_BUTTON1                     1058
#define IDC_USEBITRATE                  1060
#define IDC_JOINTSTEREO                 1061

#define IDC_MULTIASIOCHANNEL			1062
#define IDC_MULTIASIOCHANNEL2			1063

#define IDC_MONONTIME					1064
#define IDC_MONOFFTIME					1065
#define IDC_TUEONTIME					1066
#define IDC_TUEOFFTIME					1067
#define IDC_WEDONTIME					1068
#define IDC_WEDOFFTIME					1069
#define IDC_THUONTIME					1070
#define IDC_THUOFFTIME					1071
#define IDC_FRIONTIME					1072
#define IDC_FRIOFFTIME					1073
#define IDC_SATONTIME					1074
#define IDC_SATOFFTIME					1075
#define IDC_SUNONTIME					1076
#define IDC_SUNOFFTIME					1077
#define IDC_TIMEDSTREAM					1078
#define IDC_MONENABLE					1079
#define IDC_TUEENABLE					1080
#define IDC_WEDENABLE					1081
#define IDC_THUENABLE					1082
#define IDC_FRIENABLE					1083
#define IDC_SATENABLE					1084
#define IDC_SUNENABLE					1085
#define IDC_ONLABEL						1086
#define IDC_OFFLABEL					1087
#define IDC_METER_PEAK					1088
#define IDC_METER_RMS					1089
#define IDC_ATTENUATION					1090
#define IDC_LIMITER						1091
#define IDC_LIMITDB						1092
#define IDC_LIMITPREEMPH				1093
#define IDC_LIMITDBTEXT					1094
#define IDC_LIMITPREEMPHTEXT			1095
#define IDC_MINIM						1096
#define IDC_FORCEDSP					1097
#define IDC_JOINTSTEREOLABEL			1098
#define IDC_PARASTEREOLABEL				1099
#define IDC_GAINDB						1100
#define IDC_GAINDBTEXT					1101
#define IDC_ASIORATE					1102
#define IDC_CONFIGPATH					1103
#define IDC_ST_RESTORE                  32771
#define IDC_ST_EXIT                     32772
#define ID__CONFIGURE                   40001
#define ID__CONNECT                     40002
#define ID_POPUP_CONNECT                40003
#define ID_POPUP_CONFIGURE              40004
#define ID_POPUP_DELETE                 40005
#define ID_ABOUT_HELP                   40006
#define ID_ABOUT_ABOUT                  40007
#define ID__RESTORE                     40008
#define IDI_RESTORE                     40009

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        127
#define _APS_NEXT_COMMAND_VALUE         40010
#define _APS_NEXT_CONTROL_VALUE         1061
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
